# ==============================================
# DEVELOPMENT STAGE
# ==============================================
FROM node:20-alpine AS development
WORKDIR /app
ENV NODE_ENV=development
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
EXPOSE 5173
# O host 0.0.0.0 é necessário para expor o servidor para fora do container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

# ==============================================
# PRODUCTION BUILD STAGE
# ==============================================
FROM node:20-alpine AS build
WORKDIR /app
# ENV NODE_ENV=production
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
RUN npm run build

# ==============================================
# PRODUCTION FINAL STAGE (NGINX)
# ==============================================
FROM nginx:1.25-alpine AS production
# Copia os arquivos estáticos construídos
COPY --from=build /app/dist /usr/share/nginx/html
# Copia a configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]