version: '3.8'
services:
  db:
    image: postgres:15
    container_name: minha-plantinha-db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      target: dev
    container_name: minha-plantinha-backend
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./tsconfig.json:/app/tsconfig.json
      - ./.env:/app/.env
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      target: dev
    container_name: minha-plantinha-frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
